'use client';

import { ApiReferenceReact } from '@scalar/api-reference-react';
import '@scalar/api-reference-react/style.css';

// Scalar's reference UI over public/openapi.json (generated by
// scripts/build-url-params.mjs): one GET / operation whose query parameters
// are every state and instruction parameter of the viewer, so its "try it"
// form doubles as a URL builder with the right control for each type.
export function ScalarReference() {
  return (
    <div className="not-prose -mx-4 my-4">
      <ApiReferenceReact
        configuration={{
          url: '/docs/openapi.json',
          hideModels: true,
          hideDarkModeToggle: true,
          hideClientButton: true,
          showSidebar: false,
          layout: 'classic',
          theme: 'none',
        }}
      />
    </div>
  );
}
