// Writes electrobun.config.ts from the app's Vite build: Electrobun's
// `build.copy` maps files one by one into the bundle's views/ folder, and a
// Vite dist has a few hundred, so the list is generated rather than kept by
// hand. Run after `pnpm build` at the repo root; `hutch electrobun build`
// then packages dist/ as views://app/.
import { readdirSync, statSync, writeFileSync, existsSync, readFileSync } from "node:fs"
import { join, relative, dirname } from "node:path"
import { fileURLToPath } from "node:url"

const here = dirname(fileURLToPath(import.meta.url))
const dist = join(here, "..", "dist")
if (!existsSync(join(dist, "index.html"))) {
  console.error("desktop/gen-config.mjs: no ../dist/index.html, run `pnpm build` at the repo root first")
  process.exit(1)
}
const files = []
const walk = (dir) => {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name)
    if (statSync(p).isDirectory()) walk(p)
    else files.push(relative(dist, p).split("\\").join("/"))
  }
}
walk(dist)
// The docs site is not part of the desktop bundle (it is its own Next.js
// export and only lands in dist/ on the Pages deploy).
const kept = files.filter((f) => !f.startsWith("docs/"))
const version = JSON.parse(readFileSync(join(here, "..", "package.json"), "utf8")).version ?? "0.0.0"

const copy = Object.fromEntries(kept.map((f) => [`../dist/${f}`, `views/app/${f}`]))
const out = `// Generated by gen-config.mjs from ../dist: do not edit, rerun the generator.
import type { ElectrobunConfig } from "electrobun";

export default {
  app: {
    name: "Terrain Viewer",
    identifier: "com.iconem.terrain-viewer",
    version: ${JSON.stringify(version)},
  },
  build: {
    mainProcess: "cottontail",
    cottontail: {
      entrypoint: "src/bun/index.ts",
    },
    // No bundled view entrypoint: the UI is the Vite build copied below.
    views: {},
    copy: ${JSON.stringify(copy, null, 6).replace(/\n\}$/, "\n    }")},
    mac: { bundleCEF: false, codesign: false, notarize: false },
    linux: { bundleCEF: false },
    win: { bundleCEF: false },
  },
} satisfies ElectrobunConfig;
`
writeFileSync(join(here, "electrobun.config.ts"), out)
console.log(`desktop/electrobun.config.ts: ${kept.length} files from dist/`)
