// Writes electrobun.config.ts from the app's Vite build: Electrobun's
// `build.copy` maps files one by one into the bundle's views/ folder, and a
// Vite dist has a few hundred, so the list is generated rather than kept by
// hand. Run after `pnpm build` at the repo root; `hutch electrobun build`
// then packages dist/ as views://app/.
import { readdirSync, statSync, writeFileSync, existsSync } from "node:fs"
import { join, relative, dirname } from "node:path"
import { fileURLToPath } from "node:url"

const here = dirname(fileURLToPath(import.meta.url))
const dist = join(here, "..", "dist")
if (!existsSync(join(dist, "index.html"))) {
  console.error("desktop/gen-config.mjs: no ../dist/index.html, run `pnpm build` at the repo root first")
  process.exit(1)
}
const files = []
const walk = (dir) => {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name)
    if (statSync(p).isDirectory()) walk(p)
    else files.push(relative(dist, p).split("\\").join("/"))
  }
}
walk(dist)
// The docs site rides along when its static export has been merged into
// dist/docs (what the Pages deploy does: `pnpm run docs:build` then
// `cp -r docs/out/. dist/docs/`), so the sidebar's Documentation button
// resolves to views://app/docs/ offline. Without it, dist/docs holds only the
// changelog screenshots, which are left out.
// `--docs=bundled` requires the export, `--docs=online` leaves it out and
// ships a one-page stand-in (online-docs/index.html) that opens the website,
// `--docs=auto` (default) bundles it when present.
const docsArg = (process.argv.find((a) => a.startsWith("--docs=")) ?? "--docs=auto").slice("--docs=".length)
const docsExported = existsSync(join(dist, "docs", "index.html"))
if (docsArg === "bundled" && !docsExported) {
  console.error("desktop/gen-config.mjs: --docs=bundled but no ../dist/docs/index.html (run `pnpm run docs:build` and copy docs/out into dist/docs)")
  process.exit(1)
}
const docsBundled = docsArg === "bundled" || (docsArg === "auto" && docsExported)
const kept = files.filter((f) => docsBundled || !f.startsWith("docs/"))
// The app version is the build day as YYYY.M.D (a valid three-part version
// for the installers; the updater compares bundle hashes, not versions), so
// the installed app reports the same day the About section shows.
// BUILD_VERSION overrides it.
const today = new Date()
const version = process.env.BUILD_VERSION ?? `${today.getUTCFullYear()}.${today.getUTCMonth() + 1}.${today.getUTCDate()}`

// The two variants are two apps to the installer and the updater: the full
// build (docs bundled) is "com.iconem.terrain-viewer" and updates itself
// from the rolling GitHub Release (desktop.yml uploads its
// stable-<platform>-update.json and .tar.zst feed there); the light build
// has its own identifier, installs beside it, and has no feed, so it never
// updates itself into the 220 MB one.
const identifier = docsBundled ? "com.iconem.terrain-viewer" : "com.iconem.terrain-viewer-light"
const release = docsBundled ? `
  release: {
    baseUrl: "https://github.com/Iconem/terrain-viewer/releases/download/desktop-latest",
    generatePatch: false,
  },` : ""
const copy = Object.fromEntries(kept.map((f) => [`../dist/${f}`, `views/app/${f}`]))
if (!docsBundled) copy["online-docs/index.html"] = "views/app/docs/index.html"
const out = `// Generated by gen-config.mjs from ../dist: do not edit, rerun the generator.
import type { ElectrobunConfig } from "electrobun";

export default {
  app: {
    name: "Terrain Viewer",
    identifier: ${JSON.stringify(identifier)},
    version: ${JSON.stringify(version)},
  },${release}
  build: {
    mainProcess: "cottontail",
    cottontail: {
      entrypoint: "src/bun/index.ts",
      // bun:ffi for the Windows title-bar icon (src/bun/index.ts).
      capabilities: ["ffi"],
    },
    // No bundled view entrypoint: the UI is the Vite build copied below.
    views: {},
    copy: ${JSON.stringify(copy, null, 6).replace(/\n\}$/, "\n    }")},
    // icons/: the app favicon (public/favicon.svg) rasterised - .ico for the
    // installer, shortcut and taskbar, .iconset for the .app, .png for the
    // Linux desktop entry.
    mac: { bundleCEF: false, codesign: false, notarize: false, icons: "icons/icon.iconset" },
    linux: { bundleCEF: false, icon: "icons/icon.png" },
    win: { bundleCEF: false, icon: "icons/icon.ico" },
  },
} satisfies ElectrobunConfig;
`
writeFileSync(join(here, "electrobun.config.ts"), out)
console.log(`desktop/electrobun.config.ts: ${kept.length} files from dist/${docsBundled ? " (docs bundled)" : " (docs online: stand-in page)"}`)
